name: Android CI

on:
  push:
    branches:
      - main
      - release
      - 'feature/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: |
          BRANCH="${{ github.ref_name }}"

          if [ "$BRANCH" == "main" ]; then
            ./gradlew assembleProductionRelease
            APK_PATH="app/build/outputs/apk/production/release/app-production-release.apk"
            NEW_NAME="production-app-release.apk"

          elif [ "$BRANCH" == "release" ]; then
            ./gradlew assembleStagingRelease
            APK_PATH="app/build/outputs/apk/staging/release/app-staging-release.apk"
            NEW_NAME="staging-app-release.apk"

          elif [[ "$BRANCH" == feature/* ]]; then
            ./gradlew assembleStagingDebug
            APK_PATH="app/build/outputs/apk/staging/debug/app-staging-debug.apk"
            USERNAME=$(echo $BRANCH | cut -d'/' -f2)
            NEW_NAME="${USERNAME}-app-debug.apk"

          else
            ./gradlew assembleStagingDebug
            APK_PATH="app/build/outputs/apk/staging/debug/app-staging-debug.apk"
            NEW_NAME="unknown-app-debug.apk"
          fi

          echo "Renaming APK to $NEW_NAME"
          mv "$APK_PATH" "$NEW_NAME"
          echo "APK_NAME=$NEW_NAME" >> $GITHUB_ENV

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APK_NAME }}
          path: ${{ env.APK_NAME }}
