name: Android CI

on:
  push:
    branches:
      - main
      - release
      - 'feature/**'   # matches feature/anything
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout source
        uses: actions/checkout@v4

      # Set up JDK 17 (required for modern Android Gradle)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Cache Gradle for faster builds
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Make gradlew executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build the app
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Upload APK as workflow artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PharmaTracker-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk
